add a switch case

diff --git a/shell/cals b/shell/cals
--- a/shell/cals
+++ b/shell/cals
@@ -9,17 +9,33 @@
 function table() {
 	for n in {1..10}
 	do
-		echo "$1 * $n = $(( $1 * $n ))"
+		echo "$1 $2 $n = $(( $1 $2 $n ))"
 	done
-	while [ $n -le "20" ]
+	while [ $n -le 20 ]
 	do
 		sleep 1 #used to wait for 1sec to execute the next
-		echo "$1 * $n = $(( $1 * $n ))"
-		$(( n++ ))
+		echo "$1 $2 $n = $(( $1 $2 $n ))"
+		(( n++ ))
 	done
 		
 	return 1
 }
+
+case $2 in
+	"add") table $1 +
+		exit 1
+	;;
+	"sub") table $1 -
+		exit 1
+	;;
+	"mul") table $1 *
+		exit 1
+	;;
+	"div") table $1 /
+		exit 1
+	;;
+	*) echo "Invalid argv"
+esac
 
 if [ $2 = "+" ]
 then
@@ -32,10 +48,9 @@ then
 	else
 		ans=$(( $1 - $3 ))
 	fi
-elif [ $2 = "m" ]
+elif [ $2 = "*" ]
 then
-	table $1
-	exit 1
+	ans=$(($1 * $3))
 else
 	echo "Invalid"
 	exit #terminate the script
